
# Use an official Python runtime as a parent image
FROM python:3.11

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install any needed packages specified in requirements.txt
RUN pip install --trusted-host pypi.python.org -r requirements.txt

# Make port 3300 available to the world outside this container
EXPOSE 3300

# Define environment variable
#ENV NAME World

# Run uvicorn live server when container launches
CMD ["uvicorn", "src.api.api:app", "--host", "0.0.0.0", "--port", "80", "--reload"]

